require("dotenv").config();

// USE_MEMORY_STORE=1 wins over DATABASE_URL (tests / local e2e).
const impl =
  process.env.USE_MEMORY_STORE === "1" || !process.env.DATABASE_URL
    ? require("./memoryStore")
    : require("./dbStore");

function wrap(name) {
  return (...args) => {
    const result = impl[name](...args);
    return result instanceof Promise ? result : Promise.resolve(result);
  };
}

const methodNames = [
  "resetStore",
  "getProjects",
  "getProject",
  "createProject",
  "updateProject",
  "deleteProject",
  "getPendingProjects",
  "getAllProjectsSummary",
  "clearProjectServiceUserByName",
  "assignProjectServiceUser",
  "unassignProjectServiceUser",
  "getComponents",
  "getAdminComponents",
  "getAdminComponentDetail",
  "getComponentsByIds",
  "insertComponents",
  "getAssignedComponentIds",
  "getMyComponentIds",
  "deleteComponents",
  "archiveComponent",
  "getProjectComponentIds",
  "getAllProjectComponents",
  "addProjectComponents",
  "removeProjectComponent",
  "getMyCollaboratorProjectIds",
  "getProjectCollaboratorUserIds",
  "getProfilesByIds",
  "getTenantProfiles",
  "getAllProfiles",
  "getProfile",
  "getUserRoles",
  "getAdminUsers",
  "updateUserRole",
  "getTenant",
  "updateTenant",
  "getTenantLogo",
  "setTenantLogo",
  "clearTenantLogo",
  "getTenantEmailDomains",
  "addTenantEmailDomain",
  "deleteTenantEmailDomain",
  "listBusinessUnits",
  "getBusinessUnit",
  "createBusinessUnit",
  "updateBusinessUnit",
  "deactivateBusinessUnit",
  "listComplianceQuestions",
  "getComplianceQuestion",
  "createComplianceQuestion",
  "updateComplianceQuestion",
  "deactivateComplianceQuestion",
  "listProjectTagDefinitions",
  "getProjectTagDefinition",
  "createProjectTagDefinition",
  "updateProjectTagDefinition",
  "deactivateProjectTagDefinition",
  "getProjectTagIds",
  "setProjectTags",
  "listDiscoveryProjects",
  "getServiceUsersWithDetails",
  "createServiceUser",
  "deleteServiceUser",
  "updateServiceUserAssignment",
  "addProjectCollaborator",
  "addProjectCollaborators",
  "removeProjectCollaborator",
  "upsertProfile",
  "ensureUserRole",
  "resolveTenantByEmail",
  "createJobRun",
  "updateJobRun",
  "getJobRun",
  "listJobRuns",
  "reapStaleJobRuns",
  "upsertInventoryItems",
  "deactivateStaleInventory",
  "getInventoryItems",
  "getInventoryItem",
  "getComponentImportSettings",
  "upsertComponentImportSettings",
  "listEnvironments",
  "syncEnvironmentsFromInventory",
  "listWorkspaces",
  "syncWorkspacesFromInventory",
  "listInventoryEnvironments",
  "previewComponentImport",
  "importComponentsFromInventory",
  "upsertAgentUsageDaily",
  "deactivateStaleAgentUsage",
  "linkAgentUsageToInventory",
  "listCreditRateCards",
  "replaceCreditRateCards",
  "getAgentCreditsSummary",
];

module.exports = Object.fromEntries(methodNames.map((name) => [name, wrap(name)]));
