#!/usr/bin/env node
/**
 * Interactive generator for infra/terraform/terraform.tfvars
 *
 * Defaults follow the current hosted Runpipe layout (Linux App Service Node 22,
 * Static Web App, Postgres Flexible Server, Key Vault). Each prompt also lists
 * other SKUs / regions / network modes that are feasible for this stack.
 *
 * Usage:
 *   npm run setup:azure
 *   node infra/setup.js --yes
 *   node infra/setup.js --help
 */

const fs = require("node:fs");
const path = require("node:path");
const { execFileSync } = require("node:child_process");
const readline = require("node:readline/promises");
const { stdin: input, stdout: output } = require("node:process");

const ROOT = path.resolve(__dirname, "..");
const TF_DIR = path.join(__dirname, "terraform");
const TFVARS = path.join(TF_DIR, "terraform.tfvars");
const EXAMPLE = path.join(TF_DIR, "terraform.tfvars.example");

const SWA_REGIONS = new Set([
  "westeurope",
  "eastus2",
  "centralus",
  "westus2",
  "eastasia",
  "canadacentral",
]);

const CURRENT = {
  resourceGroup: "rg-runpipe-dev-2",
  api: "runpipe2-api",
  web: "runpipe2-web",
  postgres: "runpipe2-pg-dev",
  keyVault: "runpipe2-kv-dev",
  prefix: "runpipe2",
};

function parseArgs(argv) {
  const args = { yes: false, help: false, overwrite: false };
  for (const a of argv.slice(2)) {
    if (a === "--yes" || a === "-y") args.yes = true;
    else if (a === "--help" || a === "-h") args.help = true;
    else if (a === "--overwrite") args.overwrite = true;
    else {
      console.error(`Unknown argument: ${a}`);
      args.help = true;
    }
  }
  return args;
}

function help() {
  console.log(`
Runpipe Azure Terraform setup

Generates ${path.relative(ROOT, TFVARS)} for the Terraform in infra/terraform/.

  npm run setup:azure          Interactive (recommended)
  npm run setup:azure -- --yes Accept recommended values (new unique names)
  node infra/setup.js --help

Then:
  cd infra/terraform
  terraform init
  terraform plan
  terraform apply
`);
}

function tryAz(args) {
  const bins = process.platform === "win32" ? ["az.cmd", "az.exe", "az"] : ["az"];
  for (const bin of bins) {
    try {
      return execFileSync(bin, args, {
        encoding: "utf8",
        timeout: 4000,
        windowsHide: true,
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
    } catch {
      // try next binary
    }
  }
  return "";
}

async function publicIp() {
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), 4000);
  try {
    const res = await fetch("https://api.ipify.org?format=json", { signal: ac.signal });
    if (!res.ok) return "";
    const body = await res.json();
    return String(body.ip || "");
  } catch {
    return "";
  } finally {
    clearTimeout(timer);
  }
}

function randomSuffix() {
  const alphabet = "abcdefghijklmnopqrstuvwxyz0123456789";
  let s = "";
  for (let i = 0; i < 4; i++) s += alphabet[Math.floor(Math.random() * alphabet.length)];
  return s;
}

function hclString(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function hclBool(value) {
  return value ? "true" : "false";
}

function writeTfvars(cfg) {
  const lines = [
    "# Generated by npm run setup:azure. Do not commit (gitignored).",
    `# ${new Date().toISOString()}`,
    "",
    `subscription_id = ${hclString(cfg.subscription_id)}`,
    `prefix          = ${hclString(cfg.prefix)}`,
    `environment     = ${hclString(cfg.environment)}`,
    `location        = ${hclString(cfg.location)}`,
    `swa_location    = ${hclString(cfg.swa_location)}`,
    "",
    `resource_group_name = ${hclString(cfg.resource_group_name)}`,
    `api_name            = ${hclString(cfg.api_name)}`,
    `web_name            = ${hclString(cfg.web_name)}`,
    `postgres_name       = ${hclString(cfg.postgres_name)}`,
    `key_vault_name      = ${hclString(cfg.key_vault_name)}`,
    `name_suffix         = ${hclString(cfg.name_suffix)}`,
    "",
    `app_service_sku = ${hclString(cfg.app_service_sku)}`,
    `node_version    = ${hclString(cfg.node_version)}`,
    "",
    `postgres_sku           = ${hclString(cfg.postgres_sku)}`,
    `postgres_version       = ${hclString(cfg.postgres_version)}`,
    `postgres_storage_mb    = ${cfg.postgres_storage_mb}`,
    `postgres_ha            = ${hclBool(cfg.postgres_ha)}`,
    `postgres_network_mode  = ${hclString(cfg.postgres_network_mode)}`,
    `developer_ip           = ${hclString(cfg.developer_ip)}`,
    `extra_postgres_firewall_ips = []`,
    "",
    `swa_sku = ${hclString(cfg.swa_sku)}`,
    "",
    `enable_app_insights = ${hclBool(cfg.enable_app_insights)}`,
    `enable_nightly_jobs = ${hclBool(cfg.enable_nightly_jobs)}`,
    "",
    `entra_tenant_id   = ${hclString(cfg.entra_tenant_id)}`,
    `entra_client_id   = ${hclString(cfg.entra_client_id)}`,
    `default_tenant_id = ${hclString(cfg.default_tenant_id)}`,
    "",
  ];
  fs.writeFileSync(TFVARS, lines.join("\n"), "utf8");
}

function printBanner() {
  console.log(`
┌─────────────────────────────────────────────────────────┐
│  Runpipe Azure setup                                    │
│  Generates Terraform for the same resource shape as     │
│  the current hosted environment, plus other feasible    │
│  SKUs / regions / network modes.                        │
└─────────────────────────────────────────────────────────┘
  Current hosted names (for reference, not applied unless you pick them):
    RG ${CURRENT.resourceGroup}  ·  API ${CURRENT.api}
    SWA ${CURRENT.web}  ·  PG ${CURRENT.postgres}  ·  KV ${CURRENT.keyVault}

  Press Enter to accept the recommended value.
`);
}

async function askText(rl, label, def) {
  const hint = def === "" ? "" : ` [${def}]`;
  const raw = (await rl.question(`${label}${hint}: `)).trim();
  return raw === "" ? def : raw;
}

async function askYesNo(rl, label, defYes) {
  const hint = defYes ? "Y/n" : "y/N";
  const raw = (await rl.question(`${label} [${hint}]: `)).trim().toLowerCase();
  if (raw === "") return defYes;
  return raw === "y" || raw === "yes";
}

async function askChoice(rl, title, options, defaultIndex) {
  console.log(`\n${title}`);
  options.forEach((opt, i) => {
    const n = String(i + 1).padStart(2, " ");
    const rec = i === defaultIndex ? "  ← recommended" : "";
    console.log(` ${n}) ${opt.label}${rec}`);
    if (opt.note) console.log(`       ${opt.note}`);
  });
  const raw = (await rl.question(`Choose [${defaultIndex + 1}]: `)).trim();
  if (raw === "") return options[defaultIndex];
  const idx = Number.parseInt(raw, 10);
  if (!Number.isFinite(idx) || idx < 1 || idx > options.length) {
    console.log(`  (invalid choice, using ${options[defaultIndex].label})`);
    return options[defaultIndex];
  }
  return options[idx - 1];
}

function namesFor(style, prefix, environment, suffix) {
  const dash = suffix ? `-${suffix}` : "";
  if (style === "current") {
    return {
      resource_group_name: CURRENT.resourceGroup,
      api_name: CURRENT.api,
      web_name: CURRENT.web,
      postgres_name: CURRENT.postgres,
      key_vault_name: CURRENT.keyVault,
      prefix: CURRENT.prefix,
      name_suffix: "",
    };
  }
  const kv = `${prefix}-kv-${environment}${dash}`.replace(/_/g, "-");
  return {
    resource_group_name: `rg-${prefix}-${environment}`,
    api_name: `${prefix}-api${dash}`,
    web_name: `${prefix}-web${dash}`,
    postgres_name: `${prefix}-pg-${environment}${dash}`,
    key_vault_name: kv.length <= 24 ? kv : kv.replace(/-/g, "").slice(0, 24),
    prefix,
    name_suffix: suffix,
  };
}

function recommendedConfig({ subscriptionId, developerIp, suffix }) {
  const names = namesFor("new", "runpipe", "dev", suffix);
  return {
    subscription_id: subscriptionId,
    environment: "dev",
    location: "westeurope",
    swa_location: "westeurope",
    app_service_sku: "B1",
    node_version: "22-lts",
    postgres_sku: "B_Standard_B1ms",
    postgres_version: "16",
    postgres_storage_mb: 32768,
    postgres_ha: false,
    postgres_network_mode: "public_azure",
    developer_ip: developerIp,
    swa_sku: "Free",
    enable_app_insights: true,
    enable_nightly_jobs: false,
    entra_tenant_id: "",
    entra_client_id: "",
    default_tenant_id: "t1",
    ...names,
  };
}

function printSummary(cfg) {
  console.log(`
Selected configuration
──────────────────────
  Subscription     ${cfg.subscription_id || "(set ARM_SUBSCRIPTION_ID before apply)"}
  Resource group   ${cfg.resource_group_name}  (${cfg.location})
  API              ${cfg.api_name}   App Service ${cfg.app_service_sku} / Node ${cfg.node_version}
  Frontend         ${cfg.web_name}   Static Web App ${cfg.swa_sku} (${cfg.swa_location})
  Postgres         ${cfg.postgres_name}   ${cfg.postgres_sku} v${cfg.postgres_version}
  Network          ${cfg.postgres_network_mode}${cfg.developer_ip ? `  · laptop IP ${cfg.developer_ip}` : ""}
  Key Vault        ${cfg.key_vault_name}
  Insights         ${cfg.enable_app_insights ? "yes" : "no"}
  Nightly jobs     ${cfg.enable_nightly_jobs ? "yes (Logic App)" : "no"}
`);
}

function printNextSteps(cfg) {
  console.log(`Wrote ${path.relative(ROOT, TFVARS)}

Next:
  1. az login   (and az account set --subscription ${cfg.subscription_id || "<id>"})
  2. cd infra/terraform
  3. terraform init
  4. terraform plan
  5. terraform apply

After apply:
  • terraform output next_steps
  • npm run db:migrate -w backend   (DATABASE_URL = Key Vault secret DATABASE-URL)
  • Add the Static Web App URL to your Entra SPA redirect URIs
  • Put AZURE_STATIC_WEB_APPS_API_TOKEN and the App Service publish profile in GitHub secrets

Not provisioned here (still Portal / scripts):
  Entra app registrations, Power Platform refresh token, Power BI / Dataverse secrets.
  Optional later: Azure Container Apps instead of App Service; Front Door / WAF;
  remote Terraform state in a storage account.
`);
}

async function runInteractive(rl, base) {
  printBanner();

  let subscription_id = base.subscription_id;
  if (!subscription_id) {
    subscription_id = await askText(rl, "Azure subscription ID", "");
  } else {
    const keep = await askYesNo(rl, `Use subscription ${subscription_id}?`, true);
    if (!keep) subscription_id = await askText(rl, "Azure subscription ID", "");
  }

  const naming = await askChoice(
    rl,
    "Resource names",
    [
      {
        id: "new",
        label: "New deployment (runpipe-… plus a short unique suffix)",
        note: "Avoids clashes: App Service, Postgres, Key Vault, and SWA names are globally unique.",
      },
      {
        id: "current",
        label: `Match current hosted names (${CURRENT.api}, ${CURRENT.postgres}, …)`,
        note: "Only if you are recreating that environment. Apply will fail if the names are taken.",
      },
      {
        id: "custom",
        label: "Custom prefix",
        note: "You choose the prefix; a unique suffix is still added.",
      },
    ],
    0
  );

  const environment = await askText(rl, "Environment (dev / staging / prod)", "dev");
  let prefix = "runpipe";
  let suffix = randomSuffix();
  if (naming.id === "custom") {
    prefix = (await askText(rl, "Name prefix", "runpipe")).toLowerCase().replace(/[^a-z0-9-]/g, "");
  }
  if (naming.id === "current") suffix = "";
  else {
    const useSuffix = await askYesNo(rl, `Add unique suffix "-${suffix}" to globally unique names?`, true);
    if (!useSuffix) suffix = "";
  }

  const names = namesFor(naming.id === "current" ? "current" : "new", prefix, environment, suffix);

  const region = await askChoice(
    rl,
    "Azure region (most resources)",
    [
      { id: "westeurope", label: "West Europe", note: "EU; good default for this project. Static Web Apps is available here." },
      { id: "northeurope", label: "North Europe", note: "EU alternative. SWA will still be created in West Europe (SWA region list is smaller)." },
      { id: "germanywestcentral", label: "Germany West Central", note: "German data residency. SWA is created in West Europe." },
      { id: "eastus", label: "East US", note: "Often cheaper. SWA will use East US 2." },
      { id: "custom", label: "Other (type a location name)", note: "e.g. uksouth, francecentral, swedencentral." },
    ],
    0
  );
  let location = region.id;
  if (region.id === "custom") {
    location = (await askText(rl, "Location name", "westeurope")).toLowerCase().replace(/\s+/g, "");
  }

  let swa_location = SWA_REGIONS.has(location) ? location : "westeurope";
  if (location === "eastus") swa_location = "eastus2";
  if (swa_location !== location) {
    console.log(`  Static Web Apps is not in "${location}"; using "${swa_location}" for the frontend.`);
  }

  const plan = await askChoice(
    rl,
    "App Service plan (Linux API — current Runpipe uses Node 22 on App Service)",
    [
      { id: "B1", label: "B1 Basic", note: "Similar to a small always-available Linux plan. Best starting point." },
      { id: "F1", label: "F1 Free", note: "Fine for a short demo. No always-on, 60 CPU min/day, no VNet." },
      { id: "S1", label: "S1 Standard", note: "Deployment slots, always-on, custom domains. Sensible staging/prod step-up." },
      { id: "P1v3", label: "P1v3 Premium", note: "Autoscale / larger prod. Also feasible: Azure Container Apps if you later add a Dockerfile." },
    ],
    0
  );

  const node = await askChoice(
    rl,
    "Node runtime on App Service",
    [
      { id: "22-lts", label: "Node 22 LTS", note: "Matches CI and backend/package engines." },
      { id: "20-lts", label: "Node 20 LTS", note: "Feasible if your org standardizes on 20; 22 is preferred." },
    ],
    0
  );

  const pg = await askChoice(
    rl,
    "PostgreSQL Flexible Server SKU (current hosted DB is Flexible Server)",
    [
      { id: "B_Standard_B1ms", label: "Burstable B1ms", note: "Cheap, enough for inventory-sized data. Closest to a small dev server." },
      { id: "B_Standard_B2s", label: "Burstable B2s", note: "More burst CPU if jobs (inventory sync) feel tight on B1ms." },
      { id: "GP_Standard_D2ds_v5", label: "General Purpose D2ds v5", note: "Production: predictable CPU, can enable zone-redundant HA." },
      { id: "GP_Standard_D2s_v3", label: "General Purpose D2s v3", note: "Older GP family; still widely used and fully supported." },
    ],
    0
  );

  const pgVer = await askChoice(
    rl,
    "PostgreSQL version",
    [
      { id: "16", label: "16", note: "Current recommended major for a new Flexible Server." },
      { id: "15", label: "15", note: "Feasible if your org already standardizes on 15." },
      { id: "14", label: "14", note: "Only if you must match an existing dump." },
    ],
    0
  );

  let postgres_ha = false;
  if (pg.id.startsWith("GP_")) {
    postgres_ha = await askYesNo(rl, "Enable zone-redundant Postgres HA? (roughly 2× cost)", false);
  }

  const net = await askChoice(
    rl,
    "Postgres network access",
    [
      {
        id: "public_azure",
        label: "Public + Allow Azure services",
        note: "Matches the current hosted setup. Simplest. Any Azure tenant can reach the public endpoint — tighten later.",
      },
      {
        id: "public_app_outbound",
        label: "Public + App Service outbound IPs (+ your laptop IP)",
        note: "Tighter than Allow-Azure. After the first apply, add App Service outbound IPs to extra_postgres_firewall_ips (they are only known once the web app exists).",
      },
      {
        id: "private_endpoint",
        label: "Private Endpoint + VNet integration",
        note: "Production hardening. App Service plan cannot be F1. Laptop migrate/seed needs a jump host or temporary firewall rule.",
      },
    ],
    0
  );

  if (net.id === "private_endpoint" && plan.id === "F1") {
    console.log("  Private Endpoint needs VNet integration; bumping the App Service plan from F1 to B1.");
  }
  const app_service_sku = net.id === "private_endpoint" && plan.id === "F1" ? "B1" : plan.id;

  let developer_ip = base.developer_ip;
  if (net.id !== "private_endpoint") {
    developer_ip = await askText(
      rl,
      "Your public IP for Postgres (migrate/seed from this machine). Empty to skip",
      developer_ip
    );
  } else {
    developer_ip = "";
  }

  const swa = await askChoice(
    rl,
    "Static Web App SKU (current hosted frontend is SWA)",
    [
      { id: "Free", label: "Free", note: "Matches current. Staging environments + custom domains are limited." },
      { id: "Standard", label: "Standard", note: "SLA, more custom domains, private endpoints. Also feasible later: Front Door in front of SWA." },
    ],
    0
  );

  const enable_app_insights = await askYesNo(
    rl,
    "Create Log Analytics + Application Insights (recommended; not on the current host yet)?",
    true
  );
  const enable_nightly_jobs = await askYesNo(
    rl,
    "Create a Logic App that reads INTERNAL-JOB-TRIGGER-SECRET from Key Vault (managed identity) and POSTs inventory_sync every night UTC?",
    false
  );

  console.log("\nEntra IDs are optional here — you can paste them now or set app settings later.");
  const entra_tenant_id = await askText(rl, "Entra tenant (directory) ID", "");
  const entra_client_id = await askText(rl, "SPA app registration client ID", "");
  const default_tenant_id = await askText(rl, "Runpipe app-tenant id (seed uses t1)", "t1");

  return {
    subscription_id,
    environment,
    location,
    swa_location,
    app_service_sku,
    node_version: node.id,
    postgres_sku: pg.id,
    postgres_version: pgVer.id,
    postgres_storage_mb: 32768,
    postgres_ha,
    postgres_network_mode: net.id,
    developer_ip,
    swa_sku: swa.id,
    enable_app_insights,
    enable_nightly_jobs,
    entra_tenant_id,
    entra_client_id,
    default_tenant_id,
    ...names,
  };
}

async function main() {
  const args = parseArgs(process.argv);
  if (args.help) {
    help();
    process.exit(0);
  }

  if (!fs.existsSync(EXAMPLE)) {
    console.error("Missing Terraform example at", EXAMPLE);
    process.exit(1);
  }

  const subscriptionId = tryAz(["account", "show", "--query", "id", "-o", "tsv"]);
  const accountName = tryAz(["account", "show", "--query", "name", "-o", "tsv"]);
  if (accountName) {
    console.log(`Azure CLI: ${accountName} (${subscriptionId})`);
  } else {
    console.log("Azure CLI not logged in (or az not on PATH). You can still generate tfvars.");
  }

  const developerIp = await publicIp();
  const suffix = randomSuffix();
  let cfg = recommendedConfig({ subscriptionId, developerIp, suffix });

  if (!args.yes) {
    const rl = readline.createInterface({ input, output });
    try {
      cfg = await runInteractive(rl, cfg);
      printSummary(cfg);
      const ok = await askYesNo(rl, "Write terraform.tfvars?", true);
      if (!ok) {
        console.log("Cancelled.");
        process.exit(0);
      }
    } finally {
      rl.close();
    }
  } else {
    console.log("Using recommended defaults (new unique names, current-style SKUs).\n");
    printSummary(cfg);
  }

  if (fs.existsSync(TFVARS) && !args.yes && !args.overwrite) {
    const rl = readline.createInterface({ input, output });
    try {
      const overwrite = await askYesNo(rl, `${path.relative(ROOT, TFVARS)} already exists. Overwrite?`, true);
      if (!overwrite) {
        console.log("Cancelled.");
        process.exit(0);
      }
    } finally {
      rl.close();
    }
  }

  writeTfvars(cfg);
  printNextSteps(cfg);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
